config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  must_be_admin = Roombooking::RouteConstraints::AdminConstraint.new

  # Backend Admin Interfaces
  require 'sidekiq/web'
  require 'sidekiq/cron/web'
  require 'sidekiq/throttled/web'
  Sidekiq::Throttled::Web.enhance_queues_tab!
  mount Sidekiq::Web => '/admin/sidekiq', as: 'sidekiq', constraints: must_be_admin
  mount RailsAdmin::Engine => '/admin/back-office', as: 'rails_admin', constraints: must_be_admin

  # Admin Dashboard
  namespace :admin do
    root to: 'dashboard#index', as: 'dashboard'
    get '/system/info' => 'dashboard#info'
    post '/system/restart' => 'dashboard#restart'
    post '/system/shutdown' => 'dashboard#shutdown'
    post '/system/backup' => 'dashboard#backup'
    resources :camdram_shows, only: [:index, :create, :update] do
      post 'new_term', on: :collection
      post 'batch_import', on: :collection
      post 'manual_import', on: :collection
    end
    resources :camdram_societies, only: [:index, :create, :update]
  end

  # Searching
  namespace :search do
    get '/bookings' => 'bookings#search', as: 'bookings'
    get '/users' => 'users#search', as: 'users'
  end

  # RESTful Entities
  resources :bookings do
    post 'favourites', on: :collection
  end
  resources :camdram_shows, only: [:show, :edit, :update]
  resources :camdram_societies, only: [:show, :edit, :update]
  resources :rooms
  resources :users do
    get '2fa', to: 'two_factor_setup#show', as: 'show_2fa_qr', on: :member
    post '2fa', to: 'two_factor_setup#validate', as: 'validate_2fa_code', on: :member
    get 'validate', on: :member
    post 'impersonate', on: :member
    post 'discontinue_impersonation', on: :collection, as: 'discontinue_impersonation_of'
    delete 'logout_everywhere', on: :member
  end

  # Contact form
  get '/contact' => 'contact_form#new'
  post '/contact' => 'contact_form#create'

  # Authentication
  get '/login' => 'sessions#new'
  get '/logout' => 'sessions#destroy'
  delete '/logout' => 'sessions#destroy'
  get '/auth/2fa' => 'two_factor#new'
  post '/auth/2fa' => 'two_factor#create'
  get '/auth/:provider/callback' => 'sessions#create', as: :auth_callback
  get '/auth/failure' => 'sessions#failure', as: :auth_failure

  # Health & Performance
  health_check_routes
end

# Fallback to catch unroutable URLs. This needs to be inserted into the
# Rails router after the HighVoltage static pages dependency injection.
# See: https://github.com/thoughtbot/high_voltage/issues/275
Rails.application.config.after_initialize do |application|
  application.routes.append do
    match '*unmatched_route', to: 'application#route_not_found', via: :all
  end
end

app/controllers/admin/dashboard_controller.rb
# frozen_string_literal: true

module Admin
  class DashboardController < ApplicationController
    before_action :must_be_admin!

    def info
      render html: Rails::Info.to_html.html_safe
    end

    def restart
      log_abuse "#{current_user.to_log_s} initiated a system restart"
      if Rails.env.production?
        `/usr/bin/sudo /bin/systemctl restart roombooking.target`
      else
        render plain: 'No restart handler available; refusing to do so.'
      end
    end

    def shutdown
      log_abuse "#{current_user.to_log_s} initiated a system shutdown"
      if Rails.env.production?
        `/usr/bin/sudo /bin/systemctl stop roombooking.target`
      else
        render plain: 'No shutdown handler available; refusing to do so.'
      end
    end

    def backup
      log_abuse "#{current_user.to_log_s} downloaded a database dump"
      begin
        send_data `pg_dump -Fc roombooking_#{Rails.env}`,
          filename: "roombooking_#{Rails.env}_#{Time.zone.now.to_i}.pgdump"
      rescue StandardError => e
        Sentry.capture_exception(e)
        render plain: 'An error occurred when creating the backup!'
      end
    end
  end
end

app/views/admin/dashboard/index.html.erb
<% content_for :noindex, true %>
<% content_for :title, 'Admin' %>
<% content_for :heading, 'Site Admin' %>

<p>
  Use the options here and on following pages to configure this instance of Room Booking.
  Everything on this page is accessible to administrators only.
</p>

<%= content_tag :div, class: 'row my-3' do %>
  <%= content_tag :div, class: 'col-12' do %>
    <%= content_tag :div, class: 'card' do %>
      <%= content_tag :div, 'Setup Booking Entities', class: 'card-header' %>
      <%= content_tag :div, class: 'card-body' do %>
        <%= content_tag :p, 'Configure shows and societies from Camdram to allow them to make bookings within limits you define.', class: 'card-text mb-3' %>
        <%= link_to 'Configure Shows', admin_camdram_shows_path, class: 'btn btn-primary mt-1' %>
        <%= link_to 'Configure Societies', admin_camdram_societies_path, class: 'btn btn-primary mt-1' %>
      <% end %>
    <% end %>
  <% end %>
<% end %>

<%= content_tag :div, class: 'row my-3' do %>
  <%= content_tag :div, class: 'col-12 col-md-4' do %>
    <%= content_tag :div, class: 'card' do %>
      <%= content_tag :div, 'System Information', class: 'card-header' %>
      <%= content_tag :div, class: 'card-body' do %>
        <%= content_tag :p, 'View configuration settings.', class: 'card-text mb-3' %>
        <%= link_to 'Get Info', admin_system_info_path, class: 'btn btn-primary mt-1' %>
      <% end %>
    <% end %>
  <% end %>

  <%= content_tag :div, class: 'col-12 col-md-4 mt-3 mt-md-0' do %>
    <%= content_tag :div, class: 'card' do %>
      <%= content_tag :div, 'System Operations', class: 'card-header' %>
      <%= content_tag :div, class: 'card-body' do %>
        <%= content_tag :p, 'Quick-access to emergency controls.', class: 'card-text mb-3' %>
        <%= link_to 'Restart', admin_system_restart_path, method: :post, class: 'btn btn-warning mt-1' %>
        <%= link_to 'Shutdown ⚠', admin_system_shutdown_path, method: :post, class: 'btn btn-danger mt-1' %>
      <% end %>
    <% end %>
  <% end %>

  <%= content_tag :div, class: 'col-12 col-md-4 mt-3 mt-md-0' do %>
    <%= content_tag :div, class: 'card' do %>
      <%= content_tag :div, 'System Backup', class: 'card-header' %>
      <%= content_tag :div, class: 'card-body' do %>
        <%= content_tag :p, 'Download an archive of all stored data.', class: 'card-text mb-3' %>
        <%= link_to 'Export data', admin_system_backup_path, method: :post, class: 'btn btn-primary mt-1' %>
      <% end %>
    <% end %>
  <% end %>
<% end %>

<hr class="my-4">

<p>
  The following actions could potentially break the site and are recomended for advanced users only.
  If you feel like you're having to come here often then you should probably file a bug report or new feature request.
  <strong>
    Here be dragons!
  </strong>
</p>

<%= content_tag :div, class: 'row my-3' do %>
  <%= content_tag :div, class: 'col-12 col-md-6' do %>
    <%= content_tag :div, class: 'card' do %>
      <%= content_tag :div, 'Sidekiq Jobs', class: 'card-header' %>
      <%= content_tag :div, class: 'card-body' do %>
        <%= content_tag :p, 'View the background job queue and worker/mailer statuses.', class: 'card-text mb-3' %>
        <%= link_to 'Go to Sidekiq', sidekiq_path, class: 'btn btn-primary mt-1' %>
      <% end %>
    <% end %>
  <% end %>
  <%= content_tag :div, class: 'col-12 col-md-6 mt-3 mt-md-0' do %>
    <%= content_tag :div, class: 'card' do %>
      <%= content_tag :div, 'Back Office', class: 'card-header' %>
      <%= content_tag :div, class: 'card-body' do %>
        <%= content_tag :p, 'Access the site back end and edit model data manually.', class: 'card-text mb-3' %>
        <%= link_to 'Go to Back Office', rails_admin_path, class: 'btn btn-primary mt-1' %>
      <% end %>
    <% end %>
  <% end %>
<% end %>

app/views/admin/dashboard/view.html.erb
<% content_for :title, 'Admin' %>
<% content_for :heading, 'Site Admin' %>

<p>
  Use the options here to configure this instance of Room Booking.
  Everything on this page is accessible to administrators only.
</p>

<%= content_tag :div, class: 'card' do %>
  <%= content_tag :div, 'Setup Booking Entities', class: 'card-header' %>
  <%= content_tag :div, class: 'card-body' do %>
    <%= content_tag :p, 'Configure shows and societies from Camdram to allow them to make bookings within limits you define.', class: 'card-text' %>
    <%= link_to 'Configure Shows', admin_view_shows_path, class: 'btn btn-primary' %>
    <%= link_to 'Configure Societies', admin_view_societies_path, class: 'btn btn-primary' %>
  <% end %>
<% end %>

<hr class="my-4">

<p>
  The following actions could potentially break the site and are recomended for advanced users only.
  If you feel like you're having to come here often then you should probably file a bug report or new feature request.
  <strong>
    Here be dragons!
  </strong>
</p>

<%= content_tag :div, class: 'row' do %>
  <%= content_tag :div, class: 'col' do %>
    <%= content_tag :div, class: 'card' do %>
      <%= content_tag :div, 'Sidekiq Jobs', class: 'card-header' %>
      <%= content_tag :div, class: 'card-body' do %>
        <%= content_tag :p, 'View the background job queue and worker/mailer statuses.', class: 'card-text' %>
        <%= link_to 'Go to Sidekiq', sidekiq_path, class: 'btn btn-primary' %>
      <% end %>
    <% end %>
  <% end %>
  <%= content_tag :div, class: 'col' do %>
    <%= content_tag :div, class: 'card' do %>
      <%= content_tag :div, 'Back Office', class: 'card-header' %>
      <%= content_tag :div, class: 'card-body' do %>
        <%= content_tag :p, 'Access the site back end and edit model data manually.', class: 'card-text' %>
        <%= link_to 'Go to Back Office', rails_admin_path, class: 'btn btn-primary' %>
      <% end %>
    <% end %>
  <% end %>
<% end %>