config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  must_be_admin = Roombooking::RouteConstraints::AdminConstraint.new

  # Backend Admin Interfaces
  require 'sidekiq/web'
  require 'sidekiq/cron/web'
  require 'sidekiq/throttled/web'
  Sidekiq::Throttled::Web.enhance_queues_tab!
  mount Sidekiq::Web => '/admin/sidekiq', as: 'sidekiq', constraints: must_be_admin
  mount RailsAdmin::Engine => '/admin/back-office', as: 'rails_admin', constraints: must_be_admin

  # Admin Dashboard
  namespace :admin do
    root to: 'dashboard#index', as: 'dashboard'
    get '/system/info' => 'dashboard#info'
    post '/system/restart' => 'dashboard#restart'
    post '/system/shutdown' => 'dashboard#shutdown'
    post '/system/backup' => 'dashboard#backup'
    resources :camdram_shows, only: [:index, :create, :update] do
      post 'new_term', on: :collection
      post 'batch_import', on: :collection
      post 'manual_import', on: :collection
    end
    resources :camdram_societies, only: [:index, :create, :update]
  end

  # Searching
  namespace :search do
    get '/bookings' => 'bookings#search', as: 'bookings'
    get '/users' => 'users#search', as: 'users'
  end

  # RESTful Entities
  resources :bookings do
    post 'favourites', on: :collection
  end
  resources :camdram_shows, only: [:show, :edit, :update]
  resources :camdram_societies, only: [:show, :edit, :update]
  resources :rooms
  resources :users do
    get '2fa', to: 'two_factor_setup#show', as: 'show_2fa_qr', on: :member
    post '2fa', to: 'two_factor_setup#validate', as: 'validate_2fa_code', on: :member
    get 'validate', on: :member
    post 'impersonate', on: :member
    post 'discontinue_impersonation', on: :collection, as: 'discontinue_impersonation_of'
    delete 'logout_everywhere', on: :member
  end

  # Contact form
  get '/contact' => 'contact_form#new'
  post '/contact' => 'contact_form#create'

  # Authentication
  get '/login' => 'sessions#new'
  get '/logout' => 'sessions#destroy'
  delete '/logout' => 'sessions#destroy'
  get '/auth/2fa' => 'two_factor#new'
  post '/auth/2fa' => 'two_factor#create'
  get '/auth/:provider/callback' => 'sessions#create', as: :auth_callback
  get '/auth/failure' => 'sessions#failure', as: :auth_failure

  # Health & Performance
  health_check_routes
end

# Fallback to catch unroutable URLs. This needs to be inserted into the
# Rails router after the HighVoltage static pages dependency injection.
# See: https://github.com/thoughtbot/high_voltage/issues/275
Rails.application.config.after_initialize do |application|
  application.routes.append do
    match '*unmatched_route', to: 'application#route_not_found', via: :all
  end
end

app/views/admin/index.html.erb
<% content_for :title, 'Admin' %>
<% content_for :heading, 'Site Admin' %>

<p>
  Use the options here to configure this instance of Room Booking.
  Everything on this page is accessible to administrators only.
</p>

<%= content_tag :div, class: 'card' do %>
  <%= content_tag :div, 'Setup Booking Entities', class: 'card-header' %>
  <%= content_tag :div, class: 'card-body' do %>
    <%= content_tag :p, 'Configure shows and societies from Camdram to allow them to make bookings within limits you define.', class: 'card-text' %>
    <%= link_to 'Configure Shows', admin_shows_url, class: 'btn btn-primary' %>
    <%= link_to 'Configure Societies', admin_societies_url, class: 'btn btn-primary' %>
  <% end %>
<% end %>

<hr class="my-4">

<p>
  The following actions could potentially break the site and are recomended for advanced users only.
  If you feel like you're having to come here often then you should probably file a bug report or new feature request.
  <strong>
    Here be dragons!
  </strong>
</p>

<%= content_tag :div, class: 'row' do %>
  <%= content_tag :div, class: 'col' do %>
    <%= content_tag :div, class: 'card' do %>
      <%= content_tag :div, 'Sidekiq Jobs', class: 'card-header' %>
      <%= content_tag :div, class: 'card-body' do %>
        <%= content_tag :p, 'View the background job queue and worker/mailer statuses.', class: 'card-text' %>
        <%= link_to 'Go to Sidekiq', sidekiq_url, class: 'btn btn-primary' %>
      <% end %>
    <% end %>
  <% end %>
  <%= content_tag :div, class: 'col' do %>
    <%= content_tag :div, class: 'card' do %>
      <%= content_tag :div, 'Back Office', class: 'card-header' %>
      <%= content_tag :div, class: 'card-body' do %>
        <%= content_tag :p, 'Access the site back end and edit model data manually.', class: 'card-text' %>
        <%= link_to 'Go to Back Office', rails_admin_url, class: 'btn btn-primary' %>
      <% end %>
    <% end %>
  <% end %>
<% end %>

app/views/admin/view_camdram_shows.html.erb
<% content_for :title, 'Configure Shows' %>
<% content_for :heading, 'Configure Shows' %>

<p>
  Here you can import shows from Camdram that aren't yet known to the internals of Room Booking.
  Once they're imported you can activate and deactivate them, as well as set limits on the number of bookings they're allowed.
</p>

<table class="table table-condensed table-bordered table-hover">
  <thead>
    <%= content_tag :tr do %>
      <%= content_tag(:td, 'Name') %>
      <%= content_tag(:td, 'Actions') %>
    <% end %>
  </thead>
  <tbody>
    <% @shows.each do |show| %>
      <%= content_tag :tr do %>
        <%= content_tag(:td, show.name) %>
        <%= content_tag :td do %>
          <%= actions_for_show show %>
        <% end %>
      <% end %>
    <% end %>
  </tbody>
</table>

app/views/admin/view_camdram_societies.html.erb
<% content_for :title, 'Configure Societies' %>
<% content_for :heading, 'Configure Societies' %>

<p>
  Here you can import societies from Camdram that aren't yet known to the internals of Room Booking.
  Once they're imported you can activate and deactivate them, as well as set limits on the number of bookings they're allowed.
</p>

<table class="table table-condensed table-bordered table-hover">
  <thead>
    <%= content_tag :tr do %>
      <%= content_tag(:td, 'Name') %>
      <%= content_tag(:td, 'Actions') %>
    <% end %>
  </thead>
  <tbody>
    <% @societies.each do |society| %>
      <%= content_tag :tr do %>
        <%= content_tag(:td, society.name) %>
        <%= content_tag :td do %>
          <%= actions_for_society society %>
        <% end %>
      <% end %>
    <% end %>
  </tbody>
</table>