config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  must_be_admin = Roombooking::RouteConstraints::AdminConstraint.new

  # Backend Admin Interfaces
  require 'sidekiq/web'
  require 'sidekiq/cron/web'
  require 'sidekiq/throttled/web'
  Sidekiq::Throttled::Web.enhance_queues_tab!
  mount Sidekiq::Web => '/admin/sidekiq', as: 'sidekiq', constraints: must_be_admin
  mount RailsAdmin::Engine => '/admin/back-office', as: 'rails_admin', constraints: must_be_admin

  # Admin Dashboard
  namespace :admin do
    root to: 'dashboard#index', as: 'dashboard'
    get '/system/info' => 'dashboard#info'
    post '/system/restart' => 'dashboard#restart'
    post '/system/shutdown' => 'dashboard#shutdown'
    post '/system/backup' => 'dashboard#backup'
    resources :camdram_shows, only: [:index, :create, :update] do
      post 'new_term', on: :collection
      post 'batch_import', on: :collection
      post 'manual_import', on: :collection
    end
    resources :camdram_societies, only: [:index, :create, :update]
  end

  # Searching
  namespace :search do
    get '/bookings' => 'bookings#search', as: 'bookings'
    get '/users' => 'users#search', as: 'users'
  end

  # RESTful Entities
  resources :bookings do
    post 'favourites', on: :collection
  end
  resources :camdram_shows, only: [:show, :edit, :update]
  resources :camdram_societies, only: [:show, :edit, :update]
  resources :rooms
  resources :users do
    get '2fa', to: 'two_factor_setup#show', as: 'show_2fa_qr', on: :member
    post '2fa', to: 'two_factor_setup#validate', as: 'validate_2fa_code', on: :member
    get 'validate', on: :member
    post 'impersonate', on: :member
    post 'discontinue_impersonation', on: :collection, as: 'discontinue_impersonation_of'
    delete 'logout_everywhere', on: :member
  end

  # Contact form
  get '/contact' => 'contact_form#new'
  post '/contact' => 'contact_form#create'

  # Authentication
  get '/login' => 'sessions#new'
  get '/logout' => 'sessions#destroy'
  delete '/logout' => 'sessions#destroy'
  get '/auth/2fa' => 'two_factor#new'
  post '/auth/2fa' => 'two_factor#create'
  get '/auth/:provider/callback' => 'sessions#create', as: :auth_callback
  get '/auth/failure' => 'sessions#failure', as: :auth_failure

  # Health & Performance
  health_check_routes
end

# Fallback to catch unroutable URLs. This needs to be inserted into the
# Rails router after the HighVoltage static pages dependency injection.
# See: https://github.com/thoughtbot/high_voltage/issues/275
Rails.application.config.after_initialize do |application|
  application.routes.append do
    match '*unmatched_route', to: 'application#route_not_found', via: :all
  end
end

app/models/camdram_society.rb
# frozen_string_literal: true

# == Schema Information
#
# Table name: camdram_societies
#
#  id            :bigint           not null, primary key
#  camdram_id    :bigint           not null
#  max_meetings  :integer          default(0), not null
#  active        :boolean          default(FALSE), not null
#  slack_webhook :string
#  created_at    :datetime         not null
#  updated_at    :datetime         not null
#  memoized_name :string
#

class CamdramSociety < ApplicationRecord
  include CamdramInteroperability
  include CamdramBookingHandling
  include DataPreservation

  has_paper_trail
  strip_attributes only: [:slack_webhook]
  uses_camdram_client_method :get_society

  has_and_belongs_to_many :users

  validates :max_meetings, numericality: {
    only_integer: true,
    greater_than_or_equal_to: 0
  }

  # Creates a CamdramSociety model from a numeric Camdram ID.
  def self.create_from_id(id)
    create_from_id_and_name(id, nil)
  end

  # Creates a CamdramSociety model from a numeric Camdram ID and name.
  def self.create_from_id_and_name(id, name)
    create! do |roombooking_society|
      roombooking_society.camdram_id = id
      roombooking_society.max_meetings = 14
      roombooking_society.active = false
      roombooking_society.memoized_name = name if name.present?
    end
  end

  # Abstraction to allow vallidation of new bookings. Returns the society's
  # currently used quota for the week beginning on the given date.
  def calculate_weekly_quota(start_of_week, bookings)
    end_of_week = start_of_week + 7.days
    quota = 0
    bookings.each do |booking|
      booking.repeat_iterator do |st, _|
        break if st >= end_of_week
        if st >= start_of_week
          quota_increase = booking.duration / 60 / 60
          if booking.purpose == 'meeting_of'
            quota += quota_increase
          end
        end
      end
    end
    quota
  end

  # Returns true if the society has exceeded it's booking quota, false
  # otherwise.
  def exceeded_weekly_quota?(quota)
    quota > max_meetings
  end
end

app/controllers/admin/camdram_societies_controller.rb
# frozen_string_literal: true

module Admin
  class CamdramSocietiesController < DashboardController
    def index
      all_tuples = Admin::SocietyRetrievalService.perform
      @society_tuples = Kaminari.paginate_array(all_tuples).page(params[:page])
    end

    def create
      respond_to do |format|
        @roombooking_society = CamdramSociety.new(create_camdram_society_params)
        @roombooking_society.active = true
        @camdram_society = @roombooking_society.camdram_object
        if @roombooking_society.save
          UserPermissionRefreshJob.perform_async
          format.js
        else
          format.js { render js: "rbModal('Import Error', 'Failed to import the specified society! #{@roombooking_society.errors.full_messages.first}.');" }
        end
      end
    end

    def update
      @roombooking_society = CamdramSociety.find(params[:id])
      @camdram_society = @roombooking_society.camdram_object
      respond_to do |format|
        if @roombooking_society.update(update_camdram_society_params)
          if update_camdram_society_params.include? :active
            format.js
          else
            format.js { head :no_content }
          end
        end
      end
    end

    private

    def create_camdram_society_params
      params.require(:camdram_society).permit(:camdram_id)
    end

    def update_camdram_society_params
      params.require(:camdram_society).permit(:max_meetings, :active)
    end
  end
end

app/controllers/camdram_societies_controller.rb
# frozen_string_literal: true

class CamdramSocietiesController < ApplicationController
  def show
    @camdram_society = CamdramSociety.find(params[:id])
    authorize! :read, @camdram_society
    @external_society = @camdram_society.camdram_object
    if @external_society.nil?
      alert = { 'class' => 'warning', 'message' => 'This society appears to have been deleted from Camdram.' }
      flash.now[:alert] = alert
      render 'layouts/blank', locals: { reason: 'camdram object does not exist' }, status: :not_found, formats: :html and return
    end
    @quota = @camdram_society.weekly_quota Time.zone.today.beginning_of_week
    @bookings = @camdram_society.bookings.where(purpose: :meeting_of)
  end

  def edit
    @camdram_society = CamdramSociety.find(params[:id])
    authorize! :edit, @camdram_society
  end

  def update
    @camdram_society = CamdramSociety.find(params[:id])
    authorize! :edit, @camdram_society
    if @camdram_society.update(camdram_society_params)
      alert = { 'class' => 'success', 'message' => "Updated #{@camdram_society.name}!" }
      flash[:alert] = alert
      redirect_to @camdram_society
    else
      alert = { 'class' => 'danger', 'message' => @camdram_society.errors.full_messages.first }
      flash.now[:alert] = alert
      render :edit
    end
  end

  private

  def camdram_society_params
    params.require(:camdram_society).permit(:slack_webhook)
  end
end

app/views/camdram_societies/_camdram_society.html.erb
<%= link_to camdram_society.name, camdram_society_path(camdram_society), class: 'list-group-item list-group-item-action' %>

app/views/camdram_societies/_form.html.erb
<%= form_with model: @camdram_society, local: true do |form| %>
  <div class="form-group row">
    <%= form.label :slack_webhook, class: 'col-sm-2 col-form-label' %>
    <div class="col-sm-10">
      <%= form.text_field :slack_webhook, class: 'form-control' %>
    </div>
  </div>
  <div class="form-group row mt-2">
    <div class="col-sm-10">
      <%= form.submit 'Save', class: 'btn btn-outline-primary' %>
    </div>
  </div>
<% end %>

app/views/camdram_societies/edit.html.erb
<% content_for :title, 'Setup Society' %>
<% content_for :heading, 'Setup Society' %>
<% content_for :controller_links do %>
  <%= link_to 'Go Back', :back, class: 'btn btn-outline-secondary my-md-1' %>
<% end %>
<%= render 'form' %>

app/views/camdram_societies/show.html.erb
<% content_for :title, @camdram_society.name %>
<% content_for :heading, @camdram_society.name %>
<% content_for :controller_links do %>
  <%= link_to 'Go Back', :back, class: 'btn btn-outline-secondary my-md-1' %>
  <%= link_to 'Setup Integrations', edit_camdram_show_path(@camdram_society),
    class: 'btn btn-outline-primary my-md-1' if can? :update, @camdram_society %>
  <%= link_to 'View on Camdram', @camdram_society.url, class: 'btn btn-outline-info my-md-1' %>
<% end %>

<%= content_tag(:h4, 'Booking Quotas for This Week') %>
<table class="table table-sm table-striped">
  <tbody>
    <%= content_tag :tr do %>
      <%= content_tag(:td, 'Meetings:', style: 'width: 10%;') %>
      <%= content_tag(:td, progress_bar(@quota, @camdram_society.max_meetings)) %>
    <% end %>
  </tbody>
</table>

<%= content_tag(:h4, 'Bookings:') %>
<div class="d-flex flex-wrap mb-3">
  <% if @bookings.count == 0 %>
    <span class="badge badge-pill badge-light mr-1 mb-1">None!</span>
  <% else %>
    <% @bookings.each do |booking| %>
      <%= link_to booking.name, booking_path(booking), class: 'badge badge-pill badge-secondary mr-1 mb-1' %>
    <% end %>
  <% end %>
</div>

<%= content_tag(:h4, 'Description') %>
<%= Roombooking::Markdown.render_like_camdram(@external_society.description) %>

<hr class="mt-5">
<p class="float-right font-italic">
  Information kindly provided by <a href="https://www.camdram.net/">Camdram</a>.
</p>