config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  must_be_admin = Roombooking::RouteConstraints::AdminConstraint.new

  # Backend Admin Interfaces
  require 'sidekiq/web'
  require 'sidekiq/cron/web'
  require 'sidekiq/throttled/web'
  Sidekiq::Throttled::Web.enhance_queues_tab!
  mount Sidekiq::Web => '/admin/sidekiq', as: 'sidekiq', constraints: must_be_admin
  mount RailsAdmin::Engine => '/admin/back-office', as: 'rails_admin', constraints: must_be_admin

  # Admin Dashboard
  namespace :admin do
    root to: 'dashboard#index', as: 'dashboard'
    get '/system/info' => 'dashboard#info'
    post '/system/restart' => 'dashboard#restart'
    post '/system/shutdown' => 'dashboard#shutdown'
    post '/system/backup' => 'dashboard#backup'
    resources :camdram_shows, only: [:index, :create, :update] do
      post 'new_term', on: :collection
      post 'batch_import', on: :collection
      post 'manual_import', on: :collection
    end
    resources :camdram_societies, only: [:index, :create, :update]
  end

  # Searching
  namespace :search do
    get '/bookings' => 'bookings#search', as: 'bookings'
    get '/users' => 'users#search', as: 'users'
  end

  # RESTful Entities
  resources :bookings do
    post 'favourites', on: :collection
  end
  resources :camdram_shows, only: [:show, :edit, :update]
  resources :camdram_societies, only: [:show, :edit, :update]
  resources :rooms
  resources :users do
    get '2fa', to: 'two_factor_setup#show', as: 'show_2fa_qr', on: :member
    post '2fa', to: 'two_factor_setup#validate', as: 'validate_2fa_code', on: :member
    get 'validate', on: :member
    post 'impersonate', on: :member
    post 'discontinue_impersonation', on: :collection, as: 'discontinue_impersonation_of'
    delete 'logout_everywhere', on: :member
  end

  # Contact form
  get '/contact' => 'contact_form#new'
  post '/contact' => 'contact_form#create'

  # Authentication
  get '/login' => 'sessions#new'
  get '/logout' => 'sessions#destroy'
  delete '/logout' => 'sessions#destroy'
  get '/auth/2fa' => 'two_factor#new'
  post '/auth/2fa' => 'two_factor#create'
  get '/auth/:provider/callback' => 'sessions#create', as: :auth_callback
  get '/auth/failure' => 'sessions#failure', as: :auth_failure

  # Health & Performance
  health_check_routes
end

# Fallback to catch unroutable URLs. This needs to be inserted into the
# Rails router after the HighVoltage static pages dependency injection.
# See: https://github.com/thoughtbot/high_voltage/issues/275
Rails.application.config.after_initialize do |application|
  application.routes.append do
    match '*unmatched_route', to: 'application#route_not_found', via: :all
  end
end

app/models/user.rb
# frozen_string_literal: true

# == Schema Information
#
# Table name: users
#
#  id               :bigint           not null, primary key
#  name             :string           not null
#  email            :string           not null
#  admin            :boolean          default(FALSE), not null
#  sysadmin         :boolean          default(FALSE), not null
#  blocked          :boolean          default(FALSE), not null
#  created_at       :datetime         not null
#  updated_at       :datetime         not null
#  validated_at     :datetime
#  validation_token :string
#  last_login       :datetime
#

class User < ApplicationRecord
  include DataPreservation

  has_paper_trail ignore: [:last_login]
  strip_attributes only: %i[name email]

  include PgSearch::Model
  pg_search_scope :search_by_name_and_email, against: %i[name email], ignoring: :accents, using: {
    tsearch: { prefix: true, dictionary: 'english' },
    dmetaphone: { any_word: true },
    trigram: { only: [:name] }
  }

  has_one :two_factor_token, dependent: :delete
  has_many :bookings, dependent: :destroy
  has_and_belongs_to_many :camdram_shows
  has_and_belongs_to_many :camdram_societies
  has_many :provider_accounts, dependent: :delete_all
  has_one :camdram_account, -> { where(provider: 'camdram') }, class_name: 'ProviderAccount'
  has_many :camdram_tokens, dependent: :delete_all
  has_one :latest_camdram_token, -> { order(created_at: :desc) }, class_name: 'CamdramToken'

  validates :name, presence: true
  validates :email, presence: true, uniqueness: true, email: true
  validate :email_verification_state_must_be_valid

  before_validation :generate_validation_token, on: :create

  after_create_commit do |user|
    EmailVerificationMailer.deliver_async.create(user.id) unless user.validated_at.present?
  end

  after_update_commit do |user|
    EmailVerificationMailer.deliver_async.update(user.id) unless user.validated_at.present?
  end

  delegate :can?, :cannot?, to: :ability
  def ability
    @ability ||= Ability.new(self)
  end

  def generate_validation_token
    self.validation_token = SecureRandom.alphanumeric(48) unless validated_at.present?
  end

  def email=(address)
    if address != self.email
      self.validated_at = nil
      generate_validation_token
    end
    super
  end

  # Returns a user from an OmniAuth::AuthHash.
  def self.from_omniauth(auth_hash)
    provider = auth_hash['provider'].to_s
    uid = auth_hash['uid'].to_s
    account = ProviderAccount.find_by(provider: provider, uid: uid)
    if account.present?
      account.user
    else
      email = auth_hash['info']['email'].downcase
      user = User.find_by(email: email)
      ActiveRecord::Base.transaction do
        PaperTrail.request.whodunnit = email
        unless user.present?
          name = auth_hash['info']['name']
          user = User.create!(name: name, email: email)
        end
        ProviderAccount.create!(provider: provider, uid: uid, user: user)
      end
      user
    end
  end

  # Used as a helper for log_abuse methods in controllers.
  def to_log_s
    "User ##{id}".freeze
  end

  # Grants administrator privileges to the user.
  def make_admin!
    update(admin: true)
  end

  # Revokes administrator privileges from the user.
  def revoke_admin!
    update(admin: false)
  end

  # Blocks the user and invalidates all their sessions.
  def block!
    update(blocked: true)
    Session.where(user_id: id).each(&:invalidate!)
  end

  # Unblocks the user.
  def unblock!
    update(blocked: false)
  end

  def refresh_permissions!
    ActiveRecord::Base.transaction do
      update(camdram_shows: authorised_camdram_shows)
      update(camdram_societies: authorised_camdram_societies)
    end
  end

  # Validates the user's account.
  def validate(token)
    if token == validation_token
      PaperTrail.request.whodunnit = id
      update(validation_token: nil, validated_at: Time.zone.now)
    else
      false
    end
  end

  # Returns the user's Camdram uid.
  def camdram_id
    camdram_account.try(:uid)
  end

  def authorised_camdram_shows
    if admin
      # Admins are authorised for all active shows that haven't been marked as dormant.
      CamdramShow.where(active: true, dormant: false)
    else
      # Poll Camdram for future shows that the user has access to.
      shows = camdram_client.user.get_shows
      shows.reject! do |show|
        performance = show.performances.last
        next if performance.present?

        last_datetime = performance.start_at
        unless performance.repeat_until.present?
          date_difference = (performance.repeat_until - performance.start_at.to_date)
          last_datetime += date_difference
        end
        last_datetime < Time.zone.now
      end
      # Then authorise any such active shows that are not dormant.
      CamdramShow.where(camdram_id: shows.map(&:id), active: true, dormant: false)
    end
  end

  def authorised_camdram_societies
    if admin
      # Admins are authorised for all active societies.
      CamdramSociety.where(active: true)
    else
      # Poll Camdram for any societies that the user has access to.
      societies = camdram_client.user.get_societies
      # Then authorise any such active societies.
      CamdramSociety.where(camdram_id: societies.map(&:id), active: true)
    end
  end

  # Either the user's email has been verified, in which case there should be no
  # token, or we are waiting for validation and the datetime field should be blank.
  def email_verification_state_must_be_valid
    if validated_at.nil? && validation_token.nil?
      errors.add(:validation_token, 'should be present if email is not validated.')
    end
    if validated_at.present? && validation_token.present?
      errors.add(:validation_token, 'should be blank if email is validated.')
    end
  end

  private

  # Private method to create a Camdram client with the user's OAuth access
  # token. This client will be able to act as the user and view the list of
  # shows and societies the user administers.
  def camdram_client
    token = latest_camdram_token
    raise Roombooking::CamdramApi::NoAccessToken, 'No Camdram tokens found for the user' unless token.present?

    token_hash = {
      access_token: token.access_token,
      refresh_token: token.refresh_token,
      expires_at: token.expires_at
    }
    Roombooking::CamdramApi::ClientFactory.new(token_hash)
  end
end

app/controllers/search/users_controller.rb
# frozen_string_literal: true

module Search
  class UsersController < ApplicationController
    before_action :must_be_admin!

    def search
      query = params['q']
      page = params['page']
      @users = User.order(name: :asc)
                   .accessible_by(current_ability, :read)
                   .search_by_name_and_email(query)
                   .page(page)
    end
  end
end

app/controllers/users_controller.rb
# frozen_string_literal: true

class UsersController < ApplicationController
  before_action :must_be_admin!, only: :impersonate

  def index
    @users = User.accessible_by(current_ability, :read).page(params[:page])
  end

  def edit
    @user = User.find(params[:id])
    authorize! :edit, @user
  end

  def update
    @user = User.find(params[:id])
    authorize! :edit, @user
    if @user.update(user_params)
      alert = { 'class' => 'success', 'message' => 'Account updated!' }
      flash[:alert] = alert
      redirect_to @user
    else
      alert = { 'class' => 'danger', 'message' => @user.errors.full_messages.first }
      flash.now[:alert] = alert
      render :edit
    end
  end

  def show
    @user = User.find(params[:id])
    authorize! :read, @user
  end

  # Validates a user's email when their account is first created.
  def validate
    user = User.find(params[:id])
    if user.validate(params[:token])
      log_abuse "#{user.to_log_s} validated their account"
      alert = { 'class' => 'success', 'message' => 'You have successfully validated your user account! Please now login.' }
      flash[:alert] = alert
      redirect_to root_path
    else
      log_abuse "#{user.to_log_s} attempted to validated their account, but failed"
      alert = { 'class' => 'danger', 'message' => 'Something went wrong when validating your user account.' }
      flash.now[:alert] = alert
      render 'layouts/blank', locals: { reason: 'user validation failed' }, status: :forbidden
    end
  end

  # Allows an administrator to impersonate a user.
  def impersonate
    new_user = User.find(params[:id])
    log_abuse "#{current_user.to_log_s} started impersonating #{new_user.to_log_s}"
    session[:uid] = new_user.id
    redirect_to new_user
  end

  # Stops an impersonation and returns the user to their rightful account.
  def discontinue_impersonation
    if user_being_impersonated?
      log_abuse "#{login_user.to_log_s} stopped impersonating #{current_user.to_log_s}"
      session[:uid] = login_user.id
    end
    redirect_to current_user # This may still refer to the user being impersonated.
  end

  # Forces a logout everywhere the user is currently logged in by invalidating all active sessions.
  def logout_everywhere
    @user = User.find(params[:id])
    authorize! :edit, @user
    log_abuse "#{login_user.to_log_s} successfully triggered a log out of all current login sessions for #{@user.to_log_s} from the session with ID #{current_session.id}"
    Session.where(user: @user, invalidated: false).map(&:invalidate!)
    alert = { 'class' => 'success', 'message' => "#{@user.name} has been logged out of all their sessions." }
    flash[:alert] = alert
    redirect_to root_url
  end

  private

  def user_params
    if user_is_admin?
      params.require(:user).permit(:name, :email, :admin, :blocked)
    else
      params.require(:user).permit(:name, :email)
    end
  end
end

app/views/users/_form.html.erb
<%= form_with model: @user, local: true do |form| %>

  <div class="form-group row">
    <%= form.label :name, class: 'col-sm-2 col-form-label' %>
    <div class="col-sm-10">
      <%= form.text_field :name, class: 'form-control' %>
    </div>
  </div>
  <div class="form-group row">
    <%= form.label :email, class: 'col-sm-2 col-form-label' %>
    <div class="col-sm-10">
      <%= form.text_field :email, class: 'form-control' %>
    </div>
  </div>
  <% if user_is_admin? %>
    <div class="form-group row">
      <%= form.label :admin, class: 'col-sm-2 col-form-label' %>
      <div class="col-sm-10">
        <%= form.check_box :admin, class: 'form-control' %>
      </div>
    </div>
    <div class="form-group row">
      <%= form.label :blocked, class: 'col-sm-2 col-form-label' %>
      <div class="col-sm-10">
        <%= form.check_box :blocked, class: 'form-control' %>
      </div>
    </div>
  <% end %>
  <div class="form-group row mt-2">
    <div class="col-sm-10">
      <%= form.submit class: 'btn btn-outline-primary' %>
    </div>
  </div>
<% end %>

app/views/users/_user.html.erb
<%= content_tag :tr do %>
  <%= content_tag(:td, 'Full Name:') %>
  <%= content_tag(:td, @user.name) %>
<% end %>
<%= content_tag :tr do %>
  <%= content_tag(:td, 'Email:') %>
  <%= content_tag(:td, @user.email) %>
<% end %>
<%= content_tag :tr do %>
  <%= content_tag(:td, 'User ID:') %>
  <%= content_tag(:td, @user.id) %>
<% end %>
<%= content_tag :tr do %>
  <%= content_tag(:td, 'Camdram ID:') %>
  <%= content_tag(:td, @user.camdram_id || 'No account associated') %>
<% end %>
<%= content_tag :tr do %>
  <%= content_tag(:td, 'Administrator:') %>
  <%= content_tag(:td, @user.admin?.humanize) %>
<% end %>
<%= content_tag :tr do %>
  <%= content_tag(:td, 'Blocked:') %>
  <%= content_tag(:td, @user.blocked?.humanize) %>
<% end %>
<%= content_tag :tr do %>
  <%= content_tag(:td, 'Account Created:') %>
  <%= content_tag(:td, british_date_and_time(@user.created_at)) %>
<% end %>

app/views/users/edit.html.erb
<% content_for :title, 'Edit User' %>
<% content_for :heading, 'Edit User' %>
<% content_for :controller_links do %>
  <%= link_to 'Back to Users', users_path, class: 'btn btn-outline-secondary my-md-1' %>
<% end %>
<%= render 'form' %>

app/views/users/index.html.erb
<% content_for :noindex, true %>
<% content_for :title, 'Users' %>
<% content_for :heading, 'Registered Users' %>

<p>
  Only administrators can view a list of all registered users.
</p>

<% if user_is_admin? %>
  <p>
    <%= form_tag search_users_path, class: 'form-inline', method: :get do %>
      <%= search_field_tag :q, '', placeholder: 'Search users', class: 'form-control mr-sm-2' %>
      <%= submit_tag 'Search', class: 'btn btn-outline-primary my-2 my-sm-0'  %>
    <% end  %>
  </p>
<% end %>

<p>
  <%= page_entries_info @users %>
</p>

<table class="table table-condensed table-bordered table-hover">
  <thead>
    <%= content_tag :tr do %>
      <%= content_tag(:td, 'Full Name') %>
      <%= content_tag(:td, 'Email Address') %>
    <% end %>
  </thead>
  <tbody>
    <% @users.each do |user| %>
      <%= content_tag :tr do %>
        <%= content_tag(:td, link_to(user.name, user)) %>
        <%= content_tag(:td, user.email) %>
      <% end %>
    <% end %>
  </tbody>
</table>

<%= paginate @users %>

app/views/users/show.html.erb
<% content_for :noindex, true %>
<% content_for :title, @user.name %>
<% content_for :heading, 'User Details' %>
<% content_for :controller_links do %>
  <%= link_to 'Back to Users', users_path, class: 'btn btn-outline-secondary my-md-1' %>
  <% if user_is_admin? && @user != current_user && @user != login_user %>
    <%= link_to 'Impersonate', impersonate_user_path(@user), method: :post, class: 'btn btn-outline-warning my-md-1' %>
  <% end %>
  <%= link_to 'Edit', edit_user_path(@user), class: 'btn btn-outline-primary my-md-1' if can? :edit, @user %>
<% end %>

<p>
  This page list all the information we have on file for you, including your email which is used for notifications.
  Please take a moment to make sure it's accurate!
  Nobody else can view this page and we promise never to share this data with anyone.
  Any shows or societies which you can make booking on behalf of will also be listed below.
  You'll need to be authorised as an 'admin' for that show or society on Camdram for it to appear.
</p>

<%= content_tag :div, class: 'row no-gutters' do %>
  <%= content_tag :div, class: 'col-md-auto' do %>
    <%= content_tag :div, class: 'container' do %>
      <%= gravatar_image_tag(@user.email, alt: @user.name, class: 'rounded mx-auto d-block', gravatar: { size: 200, secure: true }) %>
      <p class="text-center"><%= link_to 'Setup Gravatar', 'https://en.gravatar.com' %></p>
    <% end %>
  <% end %>
  <%= content_tag :div, class: 'col' do %>
    <table class="table table-sm table-striped table-bordered mb-0">
      <tbody>
        <%= render @user %>
      </tbody>
    </table>
    <%= link_to 'Setup 2FA', show_2fa_qr_user_path(@user), class: 'btn btn-outline-primary mt-3' %>
    <%= link_to 'Logout Everywhere', logout_everywhere_user_path(@user), class: 'btn btn-outline-danger mt-3', method: :delete %>
  <% end %>
<% end %>

<hr class="mt-4 mb-1">

<%= content_tag :div, class: 'row' do %>
  <small class="col-12 mb-4 form-text text-muted">
    Information here is obtained asynchronously and may take several minutes to reflect that on Camdram.
  </small>
  <%= content_tag :div, class: 'col-12 col-md-6 mb-3' do %>
    <% if @user == current_user %>
      <%= content_tag(:h4, 'My Shows:') %>
    <% else %>
      <%= content_tag(:h4, "User's Shows:") %>
    <% end %>
    <div class="list-group list-group-flush">
      <% if @user.camdram_shows.nil? %>
        <div class="list-group-item list-group-item-action">Unknown!</div>
      <% elsif @user.camdram_shows.count == 0 %>
        <div class="list-group-item list-group-item-action">None!</div>
      <% else %>
        <%= render @user.camdram_shows %>
      <% end %>
    </div>
  <% end %>
  <%= content_tag :div, class: 'col-12 col-md-6 mb-3' do %>
    <% if @user == current_user %>
      <%= content_tag(:h4, 'My Societies:') %>
    <% else %>
      <%= content_tag(:h4, "User's Societies:") %>
    <% end %>
    <div class="list-group list-group-flush">
      <% if @user.camdram_societies.nil? %>
        <div class="list-group-item list-group-item-action">Unknown!</div>
      <% elsif @user.camdram_societies.count == 0 %>
        <div class="list-group-item list-group-item-action">None!</div>
      <% else %>
        <%= render @user.camdram_societies %>
      <% end %>
    </div>
  <% end %>
<% end %>